import fs from 'node:fs';
import * as THREE from 'three';
import {FBXLoader} from 'three/examples/jsm/loaders/FBXLoader.js';
import {GLTFExporter} from 'three/examples/jsm/exporters/GLTFExporter.js';
import {mergeVertices} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(r=>{this.result=r;this.onloadend?.();});}readAsDataURL(blob){blob.arrayBuffer().then(r=>{this.result='data:'+blob.type+';base64,'+Buffer.from(r).toString('base64');this.onloadend?.();});}};
const muscular=process.argv[2]==='muscles';const layer=muscular?'muscles':'nerves';
const b=fs.readFileSync('sources/'+(muscular?'Muscular':'Nervous')+'System100.fbx');const original=new FBXLoader().parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');original.updateMatrixWorld(true);
const group=new THREE.Group(),entries=[];const regionRules={head:/head|face|facial|mastica|crani|pharyng|tongue|ocular|optic|trigem|laryn|mandib|ophthalm|olfact|glossoph|vestib|cochlear|trochlear|abducens|oculomotor/i,spine:/back|vertebra|neck|capitis|colli|scalen|sternocleido|longissimus|iliocostalis|multifid|spinal|cauda/i,thorax:/thorax|thoracic|abdomin|intercostal|diaphragm|pectoral/i,arms:/upper_limb|shoulder|brachi|forearm|hand|deltoid|axillary|median_nerve|radial_nerve|ulnar_nerve|musculocutaneous/i,pelvis:/pelvi|glute|psoas|iliacus|piriform|pudendal|obturator|inguinal|iliohypo/i,legs:/lower_limb|thigh|_leg|foot|sciatic|femoral|fibular|tibial|sural|plantar/i};
original.traverse(object=>{if(!object.isMesh||object.geometry.attributes.position.count<=36)return;const oldMats=Array.isArray(object.material)?object.material:[object.material];const eligible=muscular?oldMats.some(m=>!/capsule|bursa|ligament|fascia|cartilage|__DEFAULT/i.test(m.name)):oldMats.some(m=>/^Nerve/.test(m.name))||/^Spinal_cord$/.test(object.name);if(!eligible)return;if(!muscular&&/Stria_terminalis|Optic_tract|Optic_chiasm/.test(object.name))return;
let geometry=object.geometry.clone();if(geometry.index)geometry=geometry.toNonIndexed();for(const attr of Object.keys(geometry.attributes))if(!['position','normal'].includes(attr))geometry.deleteAttribute(attr);const colors=new Float32Array(geometry.attributes.position.count*3);const paint=(start,count,material)=>{const color=new THREE.Color(muscular?(/tendon/i.test(material?.name||'')?0xd6bcaf:0xae534b):0xefc75d);for(let i=start;i<start+count;i++)color.toArray(colors,i*3);};if(geometry.groups.length){for(const g of geometry.groups)paint(g.start,g.count,oldMats[g.materialIndex]);}else paint(0,geometry.attributes.position.count,oldMats[0]);geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.clearGroups();geometry.applyMatrix4(object.matrixWorld);geometry.scale(.01,.01,.01);geometry=mergeVertices(geometry,1e-6);if(object.matrixWorld.determinant()<0){const idx=geometry.index.array;for(let t=0;t<idx.length;t+=3){const swap=idx[t];idx[t]=idx[t+2];idx[t+2]=swap;}}
const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0xffffff,vertexColors:true,roughness:.78}));mesh.name=object.name;
let sourceName=object.name.replaceAll('_',' ');if(/[lr]$/.test(sourceName))sourceName=sourceName.slice(0,-1)+'.'+sourceName.slice(-1);const ancestry=[];let parent=object;while(parent&&parent!==original){ancestry.push(parent.name);parent=parent.parent;}const regions=Object.entries(regionRules).filter(([id,rx])=>rx.test(!muscular&&id==='spine'?object.name:ancestry.join(' '))).map(([id])=>id);if(!muscular&&/Sciatic|Femoral|Obturator|Pudendal/.test(object.name)&&!regions.includes('pelvis'))regions.push('pelvis');
mesh.userData={sourceName,anatomyId:'za-'+layer+'-'+object.name,layer,regions};group.add(mesh);entries.push({id:mesh.userData.anatomyId,name:sourceName,regions,vertices:geometry.attributes.position.count});});
const exporter=new GLTFExporter();let bytes=0;const files=[];if(muscular){const chunks=[];let chunk=new THREE.Group(),vertices=0;for(const mesh of [...group.children]){const count=mesh.geometry.attributes.position.count;if(vertices+count>350000&&chunk.children.length){chunks.push(chunk);chunk=new THREE.Group();vertices=0;}chunk.add(mesh);vertices+=count;}if(chunk.children.length)chunks.push(chunk);for(let i=0;i<chunks.length;i++){const data=await exporter.parseAsync(chunks[i],{binary:true,onlyVisible:false});const file='muscles-'+i;fs.writeFileSync('dist/models/'+file+'.glb',Buffer.from(data));files.push(file);bytes+=data.byteLength;}fs.writeFileSync('dist/models/muscles-files.json',JSON.stringify(files));}else{const data=await exporter.parseAsync(group,{binary:true,onlyVisible:false});fs.writeFileSync('dist/models/'+layer+'.glb',Buffer.from(data));bytes=data.byteLength;files.push(layer);}fs.writeFileSync('dist/models/'+layer+'-catalog.json',JSON.stringify(entries,null,2));console.log({layer,structures:entries.length,bytes,files});
